language: node_js
node_js:
  - '9'
cache:
  directories:
    - node_modules
script:
  - npm run test
  - npm run lint
after_success:
  - npm run coveralls
deploy:
  provider: npm
  email: guidiego.expgames@gmail.com
  api_key:
    secure: t/GQekM1RR5eMpyxDet7rstVikzUKaGxV9jVOk62QZEET4hX3UtAya7tryq8rsw8VRXqgvMP9owJC/vPexi8UuGheWIlicv0ZP2FA3BOfmJH3ivnuX51+yTsGhjHz/zn3N7TRYXXbiHyt6ACe1SrZTKA6HymPH6c+iczwT1KAtbP1JvLnm6UqyOATp6fkFTwooY86+AWB9fZ7zi56QFz9cG5uKzU6V7H5YS08rBnWMD4f1oDJuVH5J6h7u0oH5Y+mpIOD9RM4DE/Q5PCOry+NiF0QEUIAvkPIyqsqBzgMljKYIhhlsWt4Tb7+pNYyeXcnx7FU7jjpvxwEjJqr+ECYrv0N7kTRpKvfIQPTfGmLr6V/WsektHe4xyQWQY41EGec9PYzrWGgwgVUOeKI1vgt/OfnSKpVcIpEbqMtXurYPYvSYL1oqtcUWPB0mpMCPVyF93hO8BsAqv/S17H0+U1RHTzRF0vW2yhB/gCLwEBPk1A8W2utmn93SW0rBY5DYZdL2lOgXZpfRQSFvP/t7q2MoLlW+tnyXzh3s8ULqE5HWNn/mTK+SNHSwOlfwPHUbuc4cjVe+IOYQTtSWozz/6Olxj76hHkb+cO1wNfDOdzo5KxShi0LfA9pS5OfrsUe3mVMSftC4NsrbvwGZKSdEyl1VtHSUtjuwugR3Mzkdzu6BI=
  on:
    tags: true
    repo: getdumont/emojinator
